// Generated by tools/gen_entry_guard.py - do not edit.
// randy31_orig functions a 5-byte jump can't be written over (Replace refuses them), sorted.
#pragma once

#include <cstdint>

namespace rnative {

constexpr uint32_t kUnsafeEntries[66] = {
    0x1149E,   // VertexBuffer_c::GetImpl: 3 bytes
    0x11D27,   // CATTriPolyList_t::GetTriVertexCnt: 4 bytes
    0x11D3B,   // CATGroup_t::GetColSphereCnt: 4 bytes
    0x11D5F,   // CATGroup_t::GetTriPolyListCnt: 4 bytes
    0x16485,   // FUN_10016485: branch to +4
    0x1667E,   // CATGroup_t::GetAttractorCnt: 4 bytes
    0x16688,   // DummyConnector::Archive: 3 bytes
    0x1668B,   // DummyConnector::RequestMatrix: 4 bytes
    0x19197,   // FUN_10019197: branch to +3
    0x1984A,   // FUN_1001984a: 4 bytes
    0x1984E,   // FUN_1001984e: branch to +4
    0x1998C,   // Color_t::Color_t: branch to +3
    0x1B662,   // FUN_1001b662: 4 bytes
    0x1B672,   // FUN_1001b672: 4 bytes
    0x1B69D,   // Triangle::GetIndexCount: 4 bytes
    0x1D60D,   // fun::DXError::GetFilename: 4 bytes
    0x1D611,   // fun::DXError::GetLineNo: 4 bytes
    0x1D615,   // fun::DXError::GetErrorNo: branch to +4
    0x1FD25,   // TriList::Optimize: branch to +1
    0x1FD26,   // TriList::GetTriangleList: 4 bytes
    0x23818,   // FUN_10023818: branch to +1
    0x23819,   // FUN_10023819: branch to +1
    0x24CF8,   // StateBlob_c::GetBlueprint: 4 bytes
    0x24D09,   // StateBlob_c::GetMaterial: 4 bytes
    0x24D1A,   // StateBlob_c::GetRenderTarget: branch to +4
    0x25E17,   // FUN_10025e17: 3 bytes
    0x25E1B,   // RenderStats_t::Reset: 1 bytes
    0x263DC,   // FUN_100263dc: 3 bytes
    0x263DF,   // FUN_100263df: 3 bytes
    0x278B4,   // FUN_100278b4: 4 bytes
    0x28212,   // FUN_10028212: 4 bytes
    0x40A9C,   // RMaterial_t::IsAlphaUsedAsTransparency: branch to +4
    0x40AFB,   // RMaterial_t::GetEnvTexture: branch to +4
    0x4198A,   // Randy_t::GetNumAlphaBits: 3 bytes
    0x419E0,   // FUN_100419e0: branch to +3
    0x46273,   // FUN_10046273: branch to +4
    0x47638,   // RTexture_t::GetPitch: branch to +4
    0x4E7EB,   // RVisualData_t::GetSimpleMeshArray: branch to +4
    0x4E7EF,   // RVisualData_t::GetSimpleMeshArray: branch to +4
    0x504EE,   // CATAnimBlend_t::GetAnim1: 4 bytes
    0x504F2,   // CATAnimBlend_t::GetAnim2: 4 bytes
    0x50A5B,   // FUN_10050a5b: 4 bytes
    0x52A5E,   // FUN_10052a5e: 4 bytes
    0x52A69,   // FUN_10052a69: 3 bytes
    0x6F1D5,   // FUN_1006f1d5: branch to +4
    0x6F1D9,   // FUN_1006f1d9: branch to +4
    0x6F1DD,   // FUN_1006f1dd: 4 bytes
    0x7194F,   // FUN_1007194f: branch to +1
    0x71EEF,   // FUN_10071eef: branch to +1
    0x72247,   // FUN_10072247: 3 bytes
    0x7388C,   // Triangle::GetIndices: branch to +3
    0x74CDF,   // FUN_10074cdf: 4 bytes
    0x74F91,   // FUN_10074f91: 4 bytes
    0x74FA2,   // FUN_10074fa2: branch to +4
    0x756F2,   // FUN_100756f2: 4 bytes
    0x75716,   // FUN_10075716: branch to +3
    0x7642D,   // FUN_1007642d: 4 bytes
    0x777B3,   // FUN_100777b3: 4 bytes
    0x78108,   // FUN_10078108: 1 bytes
    0x891FE,   // FUN_100891fe: 1 bytes
    0x89235,   // FUN_10089235: 1 bytes
    0x89236,   // FUN_10089236: 1 bytes
    0x89237,   // FUN_10089237: 1 bytes
    0x89238,   // FUN_10089238: 1 bytes
    0x89243,   // FUN_10089243: 1 bytes
    0x89244,   // FUN_10089244: 1 bytes
};

}  // namespace rnative
