// Generated by tools/gen_interface.py - do not edit.
// One naked jmp thunk per exported function. The .def points each export here, so the proxy exports
// its own code: each thunk jumps to rvk_export_targets[i], filled from the rva registry (AddressFor)
// the first time an export is called - which also runs the native install.
#include "native/native.h"

extern "C" {

void rvk_ensure_init();                         // trace.cpp: runs rnative::Install once, then fills these
extern int rvk_exports_ready;
void* rvk_export_targets[666];

__declspec(naked) void rvk_export_common()
{
    __asm {
        cmp rvk_exports_ready, 0
        jne ready
        pushad
        call rvk_ensure_init
        popad
    ready:
        mov eax, [esp]
        mov eax, dword ptr rvk_export_targets[eax * 4]
        mov [esp], eax
        ret
    }
}

__declspec(naked) void rvk_export_0() { __asm { push 0 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_1() { __asm { push 1 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_2() { __asm { push 2 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_3() { __asm { push 3 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_4() { __asm { push 4 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_5() { __asm { push 5 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_6() { __asm { push 6 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_7() { __asm { push 7 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_8() { __asm { push 8 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_9() { __asm { push 9 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_10() { __asm { push 10 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_11() { __asm { push 11 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_12() { __asm { push 12 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_13() { __asm { push 13 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_14() { __asm { push 14 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_15() { __asm { push 15 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_16() { __asm { push 16 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_17() { __asm { push 17 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_18() { __asm { push 18 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_19() { __asm { push 19 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_20() { __asm { push 20 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_21() { __asm { push 21 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_22() { __asm { push 22 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_23() { __asm { push 23 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_24() { __asm { push 24 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_25() { __asm { push 25 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_26() { __asm { push 26 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_27() { __asm { push 27 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_28() { __asm { push 28 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_29() { __asm { push 29 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_30() { __asm { push 30 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_31() { __asm { push 31 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_32() { __asm { push 32 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_33() { __asm { push 33 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_34() { __asm { push 34 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_35() { __asm { push 35 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_36() { __asm { push 36 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_37() { __asm { push 37 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_38() { __asm { push 38 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_39() { __asm { push 39 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_40() { __asm { push 40 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_41() { __asm { push 41 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_42() { __asm { push 42 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_43() { __asm { push 43 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_44() { __asm { push 44 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_45() { __asm { push 45 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_46() { __asm { push 46 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_47() { __asm { push 47 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_48() { __asm { push 48 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_49() { __asm { push 49 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_50() { __asm { push 50 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_51() { __asm { push 51 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_52() { __asm { push 52 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_53() { __asm { push 53 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_54() { __asm { push 54 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_55() { __asm { push 55 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_56() { __asm { push 56 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_57() { __asm { push 57 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_58() { __asm { push 58 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_59() { __asm { push 59 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_60() { __asm { push 60 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_61() { __asm { push 61 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_62() { __asm { push 62 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_63() { __asm { push 63 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_64() { __asm { push 64 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_65() { __asm { push 65 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_66() { __asm { push 66 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_67() { __asm { push 67 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_68() { __asm { push 68 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_69() { __asm { push 69 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_70() { __asm { push 70 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_71() { __asm { push 71 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_72() { __asm { push 72 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_73() { __asm { push 73 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_74() { __asm { push 74 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_75() { __asm { push 75 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_76() { __asm { push 76 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_77() { __asm { push 77 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_78() { __asm { push 78 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_79() { __asm { push 79 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_80() { __asm { push 80 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_81() { __asm { push 81 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_82() { __asm { push 82 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_83() { __asm { push 83 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_84() { __asm { push 84 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_85() { __asm { push 85 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_86() { __asm { push 86 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_87() { __asm { push 87 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_88() { __asm { push 88 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_89() { __asm { push 89 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_90() { __asm { push 90 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_91() { __asm { push 91 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_92() { __asm { push 92 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_93() { __asm { push 93 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_94() { __asm { push 94 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_95() { __asm { push 95 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_96() { __asm { push 96 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_97() { __asm { push 97 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_98() { __asm { push 98 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_99() { __asm { push 99 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_100() { __asm { push 100 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_101() { __asm { push 101 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_102() { __asm { push 102 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_103() { __asm { push 103 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_104() { __asm { push 104 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_105() { __asm { push 105 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_106() { __asm { push 106 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_107() { __asm { push 107 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_108() { __asm { push 108 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_109() { __asm { push 109 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_110() { __asm { push 110 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_111() { __asm { push 111 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_112() { __asm { push 112 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_113() { __asm { push 113 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_114() { __asm { push 114 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_115() { __asm { push 115 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_116() { __asm { push 116 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_117() { __asm { push 117 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_118() { __asm { push 118 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_119() { __asm { push 119 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_120() { __asm { push 120 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_121() { __asm { push 121 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_122() { __asm { push 122 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_123() { __asm { push 123 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_124() { __asm { push 124 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_125() { __asm { push 125 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_126() { __asm { push 126 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_127() { __asm { push 127 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_128() { __asm { push 128 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_129() { __asm { push 129 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_130() { __asm { push 130 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_131() { __asm { push 131 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_132() { __asm { push 132 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_133() { __asm { push 133 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_134() { __asm { push 134 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_135() { __asm { push 135 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_136() { __asm { push 136 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_137() { __asm { push 137 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_138() { __asm { push 138 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_139() { __asm { push 139 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_140() { __asm { push 140 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_141() { __asm { push 141 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_142() { __asm { push 142 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_143() { __asm { push 143 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_144() { __asm { push 144 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_145() { __asm { push 145 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_146() { __asm { push 146 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_147() { __asm { push 147 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_148() { __asm { push 148 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_149() { __asm { push 149 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_150() { __asm { push 150 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_151() { __asm { push 151 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_152() { __asm { push 152 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_153() { __asm { push 153 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_154() { __asm { push 154 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_155() { __asm { push 155 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_156() { __asm { push 156 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_157() { __asm { push 157 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_158() { __asm { push 158 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_159() { __asm { push 159 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_160() { __asm { push 160 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_161() { __asm { push 161 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_162() { __asm { push 162 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_163() { __asm { push 163 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_164() { __asm { push 164 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_165() { __asm { push 165 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_166() { __asm { push 166 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_167() { __asm { push 167 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_168() { __asm { push 168 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_169() { __asm { push 169 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_170() { __asm { push 170 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_171() { __asm { push 171 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_172() { __asm { push 172 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_173() { __asm { push 173 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_174() { __asm { push 174 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_175() { __asm { push 175 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_176() { __asm { push 176 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_177() { __asm { push 177 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_178() { __asm { push 178 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_179() { __asm { push 179 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_180() { __asm { push 180 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_181() { __asm { push 181 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_182() { __asm { push 182 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_183() { __asm { push 183 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_184() { __asm { push 184 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_185() { __asm { push 185 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_186() { __asm { push 186 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_187() { __asm { push 187 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_188() { __asm { push 188 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_189() { __asm { push 189 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_190() { __asm { push 190 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_191() { __asm { push 191 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_192() { __asm { push 192 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_193() { __asm { push 193 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_194() { __asm { push 194 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_195() { __asm { push 195 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_196() { __asm { push 196 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_197() { __asm { push 197 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_198() { __asm { push 198 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_199() { __asm { push 199 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_200() { __asm { push 200 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_201() { __asm { push 201 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_202() { __asm { push 202 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_203() { __asm { push 203 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_204() { __asm { push 204 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_205() { __asm { push 205 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_206() { __asm { push 206 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_207() { __asm { push 207 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_208() { __asm { push 208 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_209() { __asm { push 209 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_210() { __asm { push 210 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_211() { __asm { push 211 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_212() { __asm { push 212 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_213() { __asm { push 213 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_214() { __asm { push 214 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_215() { __asm { push 215 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_216() { __asm { push 216 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_217() { __asm { push 217 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_218() { __asm { push 218 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_219() { __asm { push 219 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_220() { __asm { push 220 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_221() { __asm { push 221 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_222() { __asm { push 222 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_223() { __asm { push 223 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_224() { __asm { push 224 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_225() { __asm { push 225 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_226() { __asm { push 226 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_227() { __asm { push 227 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_228() { __asm { push 228 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_229() { __asm { push 229 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_230() { __asm { push 230 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_231() { __asm { push 231 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_232() { __asm { push 232 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_233() { __asm { push 233 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_234() { __asm { push 234 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_235() { __asm { push 235 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_236() { __asm { push 236 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_237() { __asm { push 237 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_238() { __asm { push 238 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_239() { __asm { push 239 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_240() { __asm { push 240 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_241() { __asm { push 241 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_242() { __asm { push 242 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_243() { __asm { push 243 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_244() { __asm { push 244 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_245() { __asm { push 245 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_246() { __asm { push 246 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_247() { __asm { push 247 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_248() { __asm { push 248 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_249() { __asm { push 249 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_250() { __asm { push 250 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_251() { __asm { push 251 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_252() { __asm { push 252 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_253() { __asm { push 253 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_254() { __asm { push 254 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_255() { __asm { push 255 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_256() { __asm { push 256 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_257() { __asm { push 257 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_258() { __asm { push 258 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_259() { __asm { push 259 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_260() { __asm { push 260 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_261() { __asm { push 261 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_262() { __asm { push 262 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_263() { __asm { push 263 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_264() { __asm { push 264 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_265() { __asm { push 265 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_266() { __asm { push 266 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_267() { __asm { push 267 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_268() { __asm { push 268 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_269() { __asm { push 269 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_270() { __asm { push 270 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_271() { __asm { push 271 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_272() { __asm { push 272 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_273() { __asm { push 273 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_274() { __asm { push 274 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_275() { __asm { push 275 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_276() { __asm { push 276 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_277() { __asm { push 277 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_278() { __asm { push 278 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_279() { __asm { push 279 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_280() { __asm { push 280 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_281() { __asm { push 281 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_282() { __asm { push 282 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_283() { __asm { push 283 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_284() { __asm { push 284 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_285() { __asm { push 285 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_286() { __asm { push 286 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_287() { __asm { push 287 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_288() { __asm { push 288 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_289() { __asm { push 289 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_290() { __asm { push 290 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_291() { __asm { push 291 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_292() { __asm { push 292 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_293() { __asm { push 293 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_294() { __asm { push 294 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_295() { __asm { push 295 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_296() { __asm { push 296 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_297() { __asm { push 297 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_298() { __asm { push 298 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_299() { __asm { push 299 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_300() { __asm { push 300 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_301() { __asm { push 301 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_302() { __asm { push 302 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_303() { __asm { push 303 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_304() { __asm { push 304 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_305() { __asm { push 305 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_306() { __asm { push 306 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_307() { __asm { push 307 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_308() { __asm { push 308 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_309() { __asm { push 309 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_310() { __asm { push 310 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_311() { __asm { push 311 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_312() { __asm { push 312 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_313() { __asm { push 313 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_314() { __asm { push 314 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_315() { __asm { push 315 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_316() { __asm { push 316 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_317() { __asm { push 317 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_318() { __asm { push 318 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_319() { __asm { push 319 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_320() { __asm { push 320 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_321() { __asm { push 321 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_322() { __asm { push 322 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_323() { __asm { push 323 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_324() { __asm { push 324 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_325() { __asm { push 325 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_326() { __asm { push 326 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_327() { __asm { push 327 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_328() { __asm { push 328 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_329() { __asm { push 329 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_330() { __asm { push 330 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_331() { __asm { push 331 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_332() { __asm { push 332 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_333() { __asm { push 333 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_334() { __asm { push 334 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_335() { __asm { push 335 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_336() { __asm { push 336 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_337() { __asm { push 337 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_338() { __asm { push 338 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_339() { __asm { push 339 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_340() { __asm { push 340 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_341() { __asm { push 341 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_342() { __asm { push 342 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_343() { __asm { push 343 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_344() { __asm { push 344 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_345() { __asm { push 345 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_346() { __asm { push 346 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_347() { __asm { push 347 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_348() { __asm { push 348 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_349() { __asm { push 349 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_350() { __asm { push 350 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_351() { __asm { push 351 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_352() { __asm { push 352 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_353() { __asm { push 353 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_354() { __asm { push 354 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_355() { __asm { push 355 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_356() { __asm { push 356 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_357() { __asm { push 357 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_358() { __asm { push 358 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_359() { __asm { push 359 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_360() { __asm { push 360 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_361() { __asm { push 361 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_362() { __asm { push 362 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_363() { __asm { push 363 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_364() { __asm { push 364 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_365() { __asm { push 365 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_366() { __asm { push 366 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_367() { __asm { push 367 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_368() { __asm { push 368 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_369() { __asm { push 369 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_370() { __asm { push 370 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_371() { __asm { push 371 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_372() { __asm { push 372 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_373() { __asm { push 373 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_374() { __asm { push 374 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_375() { __asm { push 375 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_376() { __asm { push 376 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_377() { __asm { push 377 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_378() { __asm { push 378 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_379() { __asm { push 379 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_380() { __asm { push 380 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_381() { __asm { push 381 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_382() { __asm { push 382 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_383() { __asm { push 383 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_384() { __asm { push 384 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_385() { __asm { push 385 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_386() { __asm { push 386 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_387() { __asm { push 387 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_388() { __asm { push 388 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_389() { __asm { push 389 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_390() { __asm { push 390 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_391() { __asm { push 391 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_392() { __asm { push 392 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_393() { __asm { push 393 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_394() { __asm { push 394 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_395() { __asm { push 395 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_396() { __asm { push 396 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_397() { __asm { push 397 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_398() { __asm { push 398 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_399() { __asm { push 399 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_400() { __asm { push 400 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_401() { __asm { push 401 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_402() { __asm { push 402 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_403() { __asm { push 403 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_404() { __asm { push 404 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_405() { __asm { push 405 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_406() { __asm { push 406 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_407() { __asm { push 407 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_408() { __asm { push 408 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_409() { __asm { push 409 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_410() { __asm { push 410 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_411() { __asm { push 411 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_412() { __asm { push 412 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_413() { __asm { push 413 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_414() { __asm { push 414 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_415() { __asm { push 415 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_416() { __asm { push 416 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_417() { __asm { push 417 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_418() { __asm { push 418 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_419() { __asm { push 419 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_420() { __asm { push 420 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_421() { __asm { push 421 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_422() { __asm { push 422 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_423() { __asm { push 423 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_424() { __asm { push 424 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_425() { __asm { push 425 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_426() { __asm { push 426 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_427() { __asm { push 427 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_428() { __asm { push 428 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_429() { __asm { push 429 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_430() { __asm { push 430 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_431() { __asm { push 431 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_432() { __asm { push 432 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_433() { __asm { push 433 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_434() { __asm { push 434 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_435() { __asm { push 435 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_436() { __asm { push 436 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_437() { __asm { push 437 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_438() { __asm { push 438 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_439() { __asm { push 439 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_440() { __asm { push 440 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_441() { __asm { push 441 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_442() { __asm { push 442 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_443() { __asm { push 443 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_444() { __asm { push 444 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_445() { __asm { push 445 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_446() { __asm { push 446 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_447() { __asm { push 447 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_448() { __asm { push 448 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_449() { __asm { push 449 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_450() { __asm { push 450 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_451() { __asm { push 451 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_452() { __asm { push 452 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_453() { __asm { push 453 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_454() { __asm { push 454 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_455() { __asm { push 455 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_456() { __asm { push 456 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_457() { __asm { push 457 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_458() { __asm { push 458 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_459() { __asm { push 459 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_460() { __asm { push 460 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_461() { __asm { push 461 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_462() { __asm { push 462 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_463() { __asm { push 463 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_464() { __asm { push 464 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_465() { __asm { push 465 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_466() { __asm { push 466 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_467() { __asm { push 467 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_468() { __asm { push 468 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_469() { __asm { push 469 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_470() { __asm { push 470 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_471() { __asm { push 471 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_472() { __asm { push 472 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_473() { __asm { push 473 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_474() { __asm { push 474 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_475() { __asm { push 475 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_476() { __asm { push 476 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_477() { __asm { push 477 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_478() { __asm { push 478 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_479() { __asm { push 479 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_480() { __asm { push 480 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_481() { __asm { push 481 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_482() { __asm { push 482 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_483() { __asm { push 483 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_484() { __asm { push 484 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_485() { __asm { push 485 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_486() { __asm { push 486 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_487() { __asm { push 487 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_488() { __asm { push 488 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_489() { __asm { push 489 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_490() { __asm { push 490 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_491() { __asm { push 491 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_492() { __asm { push 492 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_493() { __asm { push 493 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_494() { __asm { push 494 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_495() { __asm { push 495 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_496() { __asm { push 496 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_497() { __asm { push 497 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_498() { __asm { push 498 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_499() { __asm { push 499 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_500() { __asm { push 500 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_501() { __asm { push 501 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_502() { __asm { push 502 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_503() { __asm { push 503 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_504() { __asm { push 504 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_505() { __asm { push 505 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_506() { __asm { push 506 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_507() { __asm { push 507 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_508() { __asm { push 508 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_509() { __asm { push 509 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_510() { __asm { push 510 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_511() { __asm { push 511 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_512() { __asm { push 512 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_513() { __asm { push 513 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_514() { __asm { push 514 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_515() { __asm { push 515 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_516() { __asm { push 516 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_517() { __asm { push 517 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_518() { __asm { push 518 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_519() { __asm { push 519 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_520() { __asm { push 520 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_521() { __asm { push 521 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_522() { __asm { push 522 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_523() { __asm { push 523 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_524() { __asm { push 524 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_525() { __asm { push 525 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_526() { __asm { push 526 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_527() { __asm { push 527 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_528() { __asm { push 528 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_529() { __asm { push 529 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_530() { __asm { push 530 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_531() { __asm { push 531 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_532() { __asm { push 532 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_533() { __asm { push 533 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_534() { __asm { push 534 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_535() { __asm { push 535 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_536() { __asm { push 536 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_537() { __asm { push 537 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_538() { __asm { push 538 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_539() { __asm { push 539 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_540() { __asm { push 540 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_541() { __asm { push 541 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_542() { __asm { push 542 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_543() { __asm { push 543 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_544() { __asm { push 544 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_545() { __asm { push 545 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_546() { __asm { push 546 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_547() { __asm { push 547 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_548() { __asm { push 548 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_549() { __asm { push 549 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_550() { __asm { push 550 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_551() { __asm { push 551 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_552() { __asm { push 552 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_553() { __asm { push 553 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_554() { __asm { push 554 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_555() { __asm { push 555 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_556() { __asm { push 556 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_557() { __asm { push 557 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_558() { __asm { push 558 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_559() { __asm { push 559 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_560() { __asm { push 560 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_561() { __asm { push 561 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_562() { __asm { push 562 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_563() { __asm { push 563 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_564() { __asm { push 564 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_565() { __asm { push 565 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_566() { __asm { push 566 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_567() { __asm { push 567 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_568() { __asm { push 568 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_569() { __asm { push 569 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_570() { __asm { push 570 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_571() { __asm { push 571 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_572() { __asm { push 572 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_573() { __asm { push 573 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_574() { __asm { push 574 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_575() { __asm { push 575 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_576() { __asm { push 576 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_577() { __asm { push 577 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_578() { __asm { push 578 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_579() { __asm { push 579 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_580() { __asm { push 580 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_581() { __asm { push 581 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_582() { __asm { push 582 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_583() { __asm { push 583 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_584() { __asm { push 584 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_585() { __asm { push 585 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_586() { __asm { push 586 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_587() { __asm { push 587 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_588() { __asm { push 588 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_589() { __asm { push 589 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_590() { __asm { push 590 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_591() { __asm { push 591 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_592() { __asm { push 592 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_593() { __asm { push 593 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_594() { __asm { push 594 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_595() { __asm { push 595 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_596() { __asm { push 596 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_597() { __asm { push 597 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_598() { __asm { push 598 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_599() { __asm { push 599 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_600() { __asm { push 600 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_601() { __asm { push 601 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_602() { __asm { push 602 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_603() { __asm { push 603 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_604() { __asm { push 604 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_605() { __asm { push 605 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_606() { __asm { push 606 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_607() { __asm { push 607 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_608() { __asm { push 608 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_609() { __asm { push 609 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_610() { __asm { push 610 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_611() { __asm { push 611 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_612() { __asm { push 612 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_613() { __asm { push 613 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_614() { __asm { push 614 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_615() { __asm { push 615 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_616() { __asm { push 616 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_617() { __asm { push 617 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_618() { __asm { push 618 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_619() { __asm { push 619 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_620() { __asm { push 620 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_621() { __asm { push 621 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_622() { __asm { push 622 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_623() { __asm { push 623 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_624() { __asm { push 624 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_625() { __asm { push 625 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_626() { __asm { push 626 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_627() { __asm { push 627 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_628() { __asm { push 628 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_629() { __asm { push 629 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_630() { __asm { push 630 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_631() { __asm { push 631 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_632() { __asm { push 632 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_633() { __asm { push 633 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_634() { __asm { push 634 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_635() { __asm { push 635 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_636() { __asm { push 636 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_637() { __asm { push 637 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_638() { __asm { push 638 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_639() { __asm { push 639 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_640() { __asm { push 640 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_641() { __asm { push 641 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_642() { __asm { push 642 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_643() { __asm { push 643 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_644() { __asm { push 644 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_645() { __asm { push 645 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_646() { __asm { push 646 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_647() { __asm { push 647 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_648() { __asm { push 648 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_649() { __asm { push 649 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_650() { __asm { push 650 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_651() { __asm { push 651 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_652() { __asm { push 652 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_653() { __asm { push 653 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_654() { __asm { push 654 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_655() { __asm { push 655 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_656() { __asm { push 656 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_657() { __asm { push 657 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_658() { __asm { push 658 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_659() { __asm { push 659 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_660() { __asm { push 660 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_661() { __asm { push 661 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_662() { __asm { push 662 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_663() { __asm { push 663 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_664() { __asm { push 664 } __asm { jmp rvk_export_common } }
__declspec(naked) void rvk_export_665() { __asm { push 665 } __asm { jmp rvk_export_common } }

static const uint32_t rvk_export_rvas[666] = {
    0x508D3,
    0x53E97,
    0x1228D,
    0x121DB,
    0x52068,
    0x51FB2,
    0x52FF8,
    0x556E2,
    0x556D2,
    0x5573D,
    0x55868,
    0x52D75,
    0x19B80,
    0x1998F,
    0x1998C,
    0x1E4A3,
    0x2EE70,
    0x2BCF9,
    0x17504,
    0x1FD01,
    0x57FE0,
    0x2A68A,
    0x2D26F,
    0x2F44E,
    0x128A1,
    0x295AB,
    0x3FE81,
    0x3FD4A,
    0x41146,
    0x41043,
    0x2BD18,
    0x166A5,
    0x458D0,
    0x44CC8,
    0x45A2F,
    0x46362,
    0x46311,
    0x135F1,
    0x47BF2,
    0x47A99,
    0x47900,
    0x4AB7A,
    0x4AB57,
    0x490E3,
    0x4B9A4,
    0x4D5E5,
    0x4D544,
    0x4E4B7,
    0x25254,
    0x4763C,
    0x19351,
    0x1920F,
    0x192BE,
    0x28A98,
    0x28A62,
    0x114F9,
    0x1153A,
    0x11581,
    0x114B1,
    0x261B9,
    0x29E76,
    0x12234,
    0x556DB,
    0x55883,
    0x52B91,
    0x1E479,
    0x17529,
    0x2D2BC,
    0x45471,
    0x46283,
    0x4ABE3,
    0x48F39,
    0x4D7D3,
    0x255B5,
    0x11614,
    0x122C9,
    0x556ED,
    0x5575B,
    0x11B40,
    0x19A47,
    0x556ED,
    0x11B18,
    0x114A1,
    0x19C93,
    0x19BB1,
    0x17FE6,
    0x11B8C,
    0x11A9B,
    0x11AA5,
    0x17EA4,
    0x2BF51,
    0x57DE0,
    0x44ED1,
    0x2CAE5,
    0x2620A,
    0x4621A,
    0x474C1,
    0x2CCAB,
    0x4C9C2,
    0x1FE9D,
    0x4CBE1,
    0x29F2D,
    0x16688,
    0x2F145,
    0x28C87,
    0x3FBD8,
    0x40916,
    0x2BCCD,
    0x44DA8,
    0x4641A,
    0x47321,
    0x4AC33,
    0x48F85,
    0x4EA04,
    0x4C947,
    0x4767A,
    0x191A0,
    0x1FD2A,
    0x52F16,
    0x4B7D9,
    0x25456,
    0x49240,
    0x48FEF,
    0x141AE,
    0x2A28E,
    0x1F90D,
    0x1FA9D,
    0x1FA50,
    0x1FAE3,
    0x4980F,
    0x23617,
    0x213E1,
    0x57A70,
    0x24A77,
    0x452CE,
    0x45769,
    0x4CE96,
    0x24844,
    0x20BED,
    0x24908,
    0x21541,
    0x23DB3,
    0x2D6FC,
    0x2CF6E,
    0x2E267,
    0x2DFC0,
    0x3FC74,
    0x13128,
    0x47060,
    0x191B8,
    0x4177F,
    0x46F06,
    0x46F95,
    0x4170C,
    0x4517B,
    0x451C4,
    0x45F49,
    0x477D6,
    0x52B0F,
    0x52B42,
    0x41CA7,
    0x47205,
    0x2CABF,
    0x14275,
    0x3FB03,
    0x52C48,
    0x52C30,
    0x504EE,
    0x504F2,
    0x45894,
    0x45430,
    0x4541A,
    0x45728,
    0x11D4F,
    0x562B5,
    0x1667E,
    0x41951,
    0x24CF8,
    0x562E1,
    0x56741,
    0x55C96,
    0x48FB4,
    0x4F898,
    0x419BD,
    0x4726B,
    0x4725E,
    0x4717D,
    0x47265,
    0x11D3F,
    0x11D3B,
    0x418EE,
    0x47693,
    0x115F4,
    0x40AFB,
    0x1D615,
    0x1E51A,
    0x1D60D,
    0x115FF,
    0x47245,
    0x47238,
    0x4706D,
    0x4723F,
    0x25E22,
    0x3EC30,
    0x47633,
    0x1149E,
    0x1B69D,
    0x7388C,
    0x20CF7,
    0x1D611,
    0x24D09,
    0x5622A,
    0x41CB5,
    0x28B1C,
    0x46277,
    0x4900C,
    0x25E2A,
    0x11B57,
    0x4198A,
    0x41984,
    0x41993,
    0x24FF1,
    0x115E8,
    0x4198D,
    0x16682,
    0x1667E,
    0x47638,
    0x2414A,
    0x11A8C,
    0x24D1A,
    0x28AE1,
    0x4E7EF,
    0x4E7EB,
    0x11605,
    0x47258,
    0x4724B,
    0x470F5,
    0x47252,
    0x115EE,
    0x5628C,
    0x261CD,
    0x26227,
    0x40ADF,
    0x24EEB,
    0x474D7,
    0x24EAF,
    0x47730,
    0x4199D,
    0x47304,
    0x52C06,
    0x52BEE,
    0x52CDD,
    0x24FFE,
    0x2AB22,
    0x11D63,
    0x11D5F,
    0x11D2B,
    0x11D27,
    0x4E7FA,
    0x4ED88,
    0x4ED3E,
    0x1FD26,
    0x4F369,
    0x4E792,
    0x4E7AB,
    0x4E7F3,
    0x52B77,
    0x4F779,
    0x4F7FC,
    0x4F723,
    0x4F0EB,
    0x2AB00,
    0x2A883,
    0x234D8,
    0x4762E,
    0x45712,
    0x54D4F,
    0x29E51,
    0x199FF,
    0x1999D,
    0x199BB,
    0x14D45,
    0x4905C,
    0x409C6,
    0x13482,
    0x141FE,
    0x29F97,
    0x2EF5F,
    0x156C3,
    0x16743,
    0x16946,
    0x16B30,
    0x16D07,
    0x17D61,
    0x16D57,
    0x16DB3,
    0x17EC8,
    0x1716A,
    0x2ADBF,
    0x2F870,
    0x12A4A,
    0x3FF26,
    0x414A7,
    0x2BDA7,
    0x45C4D,
    0x46499,
    0x46D78,
    0x13A7A,
    0x13540,
    0x47E59,
    0x4AF1A,
    0x49502,
    0x4F334,
    0x4EB53,
    0x19289,
    0x1FF60,
    0x19A7A,
    0x40A9C,
    0x472D3,
    0x475BB,
    0x41DC0,
    0x2F13A,
    0x47271,
    0x56786,
    0x49867,
    0x4F407,
    0x472A2,
    0x11AAF,
    0x4EBC4,
    0x40AFF,
    0x151E5,
    0x473A2,
    0x4734D,
    0x476C8,
    0x14E35,
    0x4E8C2,
    0x3E85B,
    0x24CE2,
    0x41E99,
    0x45289,
    0x115DD,
    0x1FD25,
    0x3012C,
    0x4721E,
    0x55837,
    0x55806,
    0x55773,
    0x557A4,
    0x557D5,
    0x44F79,
    0x49554,
    0x4CC35,
    0x577D3,
    0x4D84A,
    0x4AA1C,
    0x4A925,
    0x5536C,
    0x11632,
    0x2622D,
    0x46224,
    0x474CC,
    0x57E96,
    0x44F10,
    0x49761,
    0x4F154,
    0x45F7A,
    0x49A60,
    0x4934C,
    0x48FBE,
    0x4CABA,
    0x4D2D8,
    0x4BAAD,
    0x1668B,
    0x2BD6A,
    0x25E1B,
    0x24D1E,
    0x4B724,
    0x4BB4D,
    0x23DBC,
    0x490CA,
    0x4CC29,
    0x41E9F,
    0x2133F,
    0x4E7A3,
    0x4CC06,
    0x11B07,
    0x14F53,
    0x41755,
    0x507E5,
    0x5085C,
    0x53FE2,
    0x457E7,
    0x4506B,
    0x504F6,
    0x24CEB,
    0x47024,
    0x46FF2,
    0x46FCC,
    0x46FA2,
    0x4B997,
    0x46E5D,
    0x45253,
    0x125D7,
    0x4B3F6,
    0x3011C,
    0x4B61E,
    0x40A65,
    0x4CB8E,
    0x45329,
    0x40E5F,
    0x431C7,
    0x41876,
    0x4704C,
    0x46ED4,
    0x46EAE,
    0x46E84,
    0x452F8,
    0x300C7,
    0x300B4,
    0x30043,
    0x11B2D,
    0x11AB6,
    0x11AD4,
    0x11AE7,
    0x51F51,
    0x455A8,
    0x45516,
    0x45113,
    0x52C99,
    0x4E743,
    0x24CFC,
    0x1668F,
    0x4C9A8,
    0x55108,
    0x20BF6,
    0x11B70,
    0x40F61,
    0x16688,
    0x2BCB4,
    0x45C85,
    0x45CD9,
    0x4CB7E,
    0x24D0D,
    0x55C86,
    0x4538B,
    0x3FCDE,
    0x47038,
    0x46F63,
    0x46F3D,
    0x46F13,
    0x57A30,
    0x40BEC,
    0x253A2,
    0x1BC15,
    0x51CFC,
    0x25012,
    0x254EA,
    0x453ED,
    0x49017,
    0x40FE5,
    0x41ED1,
    0x2A8E1,
    0x4BAD6,
    0x4543D,
    0x41EC4,
    0x45DEB,
    0x45D41,
    0x14253,
    0x3FB49,
    0x28C05,
    0x28C1E,
    0x4CBBE,
    0x3ED78,
    0x4BD1B,
    0x4749D,
    0x55331,
    0x40FF8,
    0x44FA2,
    0x40A8F,
    0x55910,
    0x558F5,
    0x558A4,
    0x558BF,
    0x558DA,
    0x251AC,
    0x1AA09,
    0x1B80,
    0xB2E0,
    0x9530,
    0xB5B0,
    0xB430,
    0xB3A0,
    0xB3D0,
    0x1A10,
    0x11C0,
    0x3100,
    0x3130,
    0x1350,
    0x1250,
    0x4510,
    0xB230,
    0x1190,
    0x13A0,
    0xB690,
    0x5740,
    0x5A90,
    0x5410,
    0x4D80,
    0x5440,
    0x5510,
    0x53D0,
    0x5CC0,
    0x5CE0,
    0x4DA0,
    0x5C60,
    0x4E00,
    0x1AE0,
    0x6210,
    0x61F0,
    0xB530,
    0x4DC0,
    0x55F0,
    0x55C0,
    0x5710,
    0x1AF0,
    0x1B00,
    0x5670,
    0x4D60,
    0x4D40,
    0xB7E0,
    0x4DE0,
    0x5D50,
    0x5D10,
    0x19D0,
    0x5D00,
    0x1AF0,
    0xB750,
    0x5800,
    0x5850,
    0x5A40,
    0x52E0,
    0x4EB0,
    0x4F00,
    0x5090,
    0x4E80,
    0x5C20,
    0x4D00,
    0x4D20,
    0x5AD0,
    0x5990,
    0x5900,
    0x59F0,
    0x56E0,
    0x5630,
    0x53F0,
    0x5B50,
    0x5B80,
    0x5B00,
    0xB810,
    0xB770,
    0xB7E0,
    0x5BF0,
    0x5C40,
    0x5CA0,
    0x61D0,
    0x5C80,
    0x4CE0,
    0x5240,
    0x51C0,
    0x4F60,
    0x4FC0,
    0x50D0,
    0x4E20,
    0x5290,
    0x5200,
    0x4F90,
    0x4FF0,
    0x5110,
    0x4E50,
    0x1B10,
    0x12D0,
    0x19F0,
    0xB4E0,
    0xB620,
    0xB670,
    0xB6B0,
    0x111B0,
    0x4090,
    0x3FC0,
    0x3530,
    0x4AD0,
    0x3A60,
    0x3F30,
    0x39F0,
    0x1B60,
    0x101C0,
    0x107E0,
    0x5E90,
    0xF840,
    0x6370,
    0x6300,
    0x11480,
    0x5D60,
    0xF900,
    0xF870,
    0x11440,
    0x11460,
    0x11340,
    0x6230,
    0xB510,
    0x7090,
    0x70F0,
    0x70B0,
    0x5E30,
    0xFFE0,
    0xFF70,
    0x6F10,
    0x6E70,
    0x7120,
    0x100F0,
    0x10930,
    0x5E00,
    0x11400,
    0x5EE0,
    0x5F00,
    0x111D0,
    0xB480,
    0xB720,
    0x10290,
    0x102C0,
    0x107B0,
    0x5D90,
    0x5DB0,
    0x7090,
    0x6480,
    0xB1E0,
    0x4AB0,
    0x112D0,
    0x73A0,
    0x7210,
    0x7140,
    0x112F0,
    0x10880,
    0x10640,
    0x10710,
    0x104D0,
    0x10E50,
    0x108B0,
    0x108D0,
    0x5DD0,
    0x1000,
    0x6440,
    0x6460,
    0x5D70,
    0x5EC0,
    0x10D00,
    0x10D30,
    0x70D0,
    0x10A20,
    0x11170,
    0x11010,
    0x11420,
    0x61B0,
    0x1030,
    0x3A30,
    0xB260,
};

void rvk_install_exports()
{
    for (unsigned i = 0; i < 666; ++i) rvk_export_targets[i] = rnative::AddressFor(rvk_export_rvas[i]);
}

}  // extern "C"
