#!/usr/bin/env python3
"""Map randy31.dll's export surface and who uses it.

Reads the original randy31.dll and every other PE in the client folder with llvm-readobj and writes:
  interface/exports.tsv  one row per export: ordinal, rva, section, users, mangled, demangled
  interface/summary.md   counts per class / per importing module
  proxy/randy31.def      forwarding .def for the pass-through proxy (all exports -> randy31_orig)

Usage: tools/gen_interface.py [CLIENT_DIR]
"""
import collections
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CLIENT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else
                      pathlib.Path.home() / ".wine-prk/drive_c/linux/client")
TARGET = "randy31.dll"
ORIG = "randy31_orig"


def readobj(*args):
    return subprocess.run(["llvm-readobj", *args], capture_output=True, text=True).stdout


def sections(path):
    out = readobj("--sections", str(path))
    names = re.findall(r"Name: (\S+) \(", out)
    vas = [int(x, 16) for x in re.findall(r"VirtualAddress: (0x[0-9A-F]+)", out)]
    sizes = [int(x, 16) for x in re.findall(r"VirtualSize: (0x[0-9A-F]+)", out)]
    return list(zip(names, vas, sizes))


def section_of(secs, rva):
    for name, va, size in secs:
        if va <= rva < va + size:
            return name
    return "?"


def exports(path):
    out = readobj("--coff-exports", str(path))
    return [(int(o), n, int(r, 16)) for o, n, r in
            re.findall(r"Ordinal: (\d+)\s+Name: (\S+)\s+RVA: (0x[0-9A-F]+)", out)]


def imports_from(path, dll):
    """Names `path` imports from `dll` (case-insensitive), or None if it doesn't import it."""
    out = readobj("--coff-imports", str(path))
    names, inside, found = [], False, False
    for line in out.splitlines():
        m = re.match(r"\s+Name: (\S+)$", line)
        if m:
            inside = m.group(1).lower() == dll
            found |= inside
            continue
        m = re.match(r"\s+Symbol: (\S*) \((\d+)\)", line)
        if inside and m:
            names.append(m.group(1) or f"#{m.group(2)}")
    return names if found else None


def demangle(names):
    out = subprocess.run(["llvm-undname"], input="\n".join(names), capture_output=True,
                         text=True).stdout.splitlines()
    # llvm-undname echoes each input line, then prints the demangled form
    result, it = {}, iter(out)
    for line in it:
        if line in names and line not in result:
            result[line] = next(it, line)
    return result


def class_of(dem):
    m = re.search(r"(?:__thiscall|__cdecl|__stdcall|__fastcall|static [^(]*?|class [^(]*? |struct [^(]*? )"
                  r"\s*([A-Za-z_][\w]*)::", dem)
    return m.group(1) if m else "(free)"


def main():
    dll = CLIENT / TARGET
    secs = sections(dll)
    exps = exports(dll)

    users = collections.defaultdict(list)
    for pe in sorted(CLIENT.iterdir()):
        if pe.suffix.lower() not in (".dll", ".exe") or pe.name.lower() in (TARGET, ORIG + ".dll"):
            continue
        names = imports_from(pe, TARGET)
        if names:
            for n in names:
                users[n].append(pe.name)

    names = [n for _, n, _ in exps]
    dem = demangle(names)

    (ROOT / "interface").mkdir(exist_ok=True)
    with open(ROOT / "interface/exports.tsv", "w") as f:
        f.write("ordinal\trva\tsection\tusers\tmangled\tdemangled\n")
        for o, n, r in exps:
            f.write(f"{o}\t0x{r:06X}\t{section_of(secs, r)}\t{','.join(users.get(n, []))}\t{n}\t{dem.get(n, n)}\n")

    used = [(o, n, r) for o, n, r in exps if n in users]
    per_module = collections.Counter(m for n in users for m in users[n])
    per_class = collections.Counter(class_of(dem.get(n, n)) for _, n, _ in used)
    per_section = collections.Counter(section_of(secs, r) for _, n, r in used)
    with open(ROOT / "interface/summary.md", "w") as f:
        f.write(f"# randy31.dll interface\n\nGenerated by tools/gen_interface.py from {dll}.\n\n")
        f.write(f"- exports: {len(exps)}\n- imported by other modules: {len(used)}\n")
        f.write(f"- used exports by section: {dict(per_section)}\n\n## Importers\n\n")
        for m, c in per_module.most_common():
            f.write(f"- {m}: {c}\n")
        f.write("\n## Used exports per class\n\n")
        for c, k in per_class.most_common():
            f.write(f"- {c}: {k}\n")

    (ROOT / "proxy").mkdir(exist_ok=True)
    with open(ROOT / "proxy/randy31.def", "w") as f:
        f.write("; Generated by tools/gen_interface.py - every export forwards to the original DLL.\n")
        f.write("; Replace a line with a local definition to take over that export.\n")
        f.write("LIBRARY randy31\nEXPORTS\n")
        for o, n, r in exps:
            data = " DATA" if section_of(secs, r) != ".text" else ""
            f.write(f"    {n}={ORIG}.{n} @{o}{data}\n")

    print(f"{len(exps)} exports, {len(used)} used; importers: {dict(per_module)}")


if __name__ == "__main__":
    main()
