#!/usr/bin/env python3
"""Functions of randy31_orig.dll that can't take a 5-byte jump over their entry (proxy/native Replace refuses them):
a branch lands inside their first 5 bytes (interface/entry-targets.txt, ghidra-scripts/EntryTargets.java) or they are
shorter than 5 bytes (build/profile/orig-functions.txt, ListFunctions.java). Writes proxy/native/entry_guard.gen.h.

Usage: tools/gen_entry_guard.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
unsafe = {}
for line in open(ROOT / "interface/entry-targets.txt"):
    rva, name, offset = line.split()
    unsafe[int(rva, 16)] = f"{name}: branch to +{offset}"
for line in open(ROOT / "build/profile/orig-functions.txt"):
    rva, size, name = line.split(" ", 2)
    if int(size, 16) < 5:
        unsafe.setdefault(int(rva, 16), f"{name.strip()}: {int(size, 16)} bytes")
out = ["// Generated by tools/gen_entry_guard.py - do not edit.",
       "// randy31_orig functions a 5-byte jump can't be written over (Replace refuses them), sorted.",
       "#pragma once", "", "#include <cstdint>", "", "namespace rnative {", "",
       f"constexpr uint32_t kUnsafeEntries[{len(unsafe)}] = {{"]
out += [f"    0x{rva:05X},   // {why}" for rva, why in sorted(unsafe.items())]
out += ["};", "", "}  // namespace rnative", ""]
(ROOT / "proxy/native/entry_guard.gen.h").write_text("\n".join(out))
print(f"{len(unsafe)} unsafe entries")
