#!/usr/bin/env python3
"""Typed C++ bindings to randy31_orig.dll's exported functions, for native code that still calls the original
(proxy/native/orig_api.gen.h). From interface/exports.tsv (demangled signatures): each function becomes
`rnative::orig::Class_Method(...)` (thiscall as fastcall with an unused EDX; classes, references and pointers as
void*). Overloads get the ordinal appended. Functions returning a class by value or taking one by value are skipped.

Usage: tools/gen_orig_api.py      (writes proxy/native/orig_api.gen.h)
"""
import csv
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent

SCALARS = {
    "void": "void", "bool": "bool", "float": "float", "double": "double",
    "char": "char", "signed char": "int8_t", "unsigned char": "uint8_t",
    "short": "int16_t", "unsigned short": "uint16_t", "int": "int32_t", "unsigned int": "uint32_t",
    "long": "int32_t", "unsigned long": "uint32_t", "__int64": "int64_t", "unsigned __int64": "uint64_t",
}


def split_args(s):
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch in "<(":
            depth += 1
        elif ch in ">)":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def ctype(t):
    """C type for a demangled parameter / return type; None if unsupported (a class by value)."""
    t = t.strip()
    t = re.sub(r"\s+", " ", t)
    if t in ("void", ""):
        return "void"
    const = " const" in t or t.startswith("const ")
    if t.endswith("*") or t.endswith("&") or t.endswith("* const") or "(__" in t:
        if re.fullmatch(r"(char const|const char) ?\*", t):
            return "const char*"
        return "const void*" if const and t.count("*") + t.count("&") == 1 and not t.endswith("* const") else "void*"
    base = t.replace("const", "").strip()
    if base.startswith("enum "):
        return "int32_t"
    if base in SCALARS:
        return SCALARS[base]
    return None                                  # a class / struct by value


def main():
    rows = list(csv.reader(open(ROOT / "interface/exports.tsv"), delimiter="\t"))[1:]
    funcs, names = [], {}
    for ordinal, rva, section, users, mangled, demangled in rows:
        if section != ".text":
            continue
        m = re.match(r"(?:(?:public|protected|private): )?(static )?(virtual )?(.*?)\s*(__thiscall|__cdecl|__stdcall) "
                     r"([\w:~`' ]+?)\((.*)\)( const)?$", demangled)
        if not m:
            continue
        static, _, ret, conv, qname, args, _ = m.groups()
        if "`" in qname or "~" in qname or "operator" in qname:
            continue
        parts = qname.split("::")
        if len(parts) >= 2 and parts[-1] == parts[-2]:
            ret = "void*"                         # a constructor returns `this`
        rtype = ctype(ret) if ret != "void*" else "void*"
        if rtype is None:
            continue
        params = [] if args.strip() in ("void", "") else split_args(args)
        if "..." in params:
            continue
        ptypes = [ctype(p) for p in params]
        if any(p is None for p in ptypes):
            continue
        name = "_".join(p for p in parts if p).replace("::", "_")
        name = re.sub(r"\W", "_", name)
        funcs.append((name, int(ordinal), mangled, demangled, rtype, ptypes, conv == "__thiscall"))
        names[name] = names.get(name, 0) + 1
    out = ["// Generated by tools/gen_orig_api.py from interface/exports.tsv - do not edit.",
           "// Typed calls into randy31_orig.dll's exports (see that script). orig::Init(module) first.",
           "#pragma once", "", "#include <windows.h>", "", "#include <cstdint>", "", "namespace rnative::orig {", "",
           f"constexpr unsigned kExportCount = {len(funcs)};",
           "extern void* g_fn[kExportCount];",
           "bool Init(HMODULE orig);                // false if one is missing (logged)", "",
           "struct ExportName { const char* mangled; };",
           "extern const ExportName kExports[kExportCount];", ""]
    table = []
    for i, (name, ordinal, mangled, demangled, rtype, ptypes, thiscall) in enumerate(funcs):
        fname = name if names[name] == 1 else f"{name}_{ordinal}"
        params = ", ".join(f"{t} a{k}" for k, t in enumerate(ptypes))
        args = ", ".join(f"a{k}" for k in range(len(ptypes)))
        if thiscall:
            sig = ", ".join(["void*", "void*"] + ptypes)
            call = ", ".join(["self", "nullptr"] + ([args] if args else []))
            decl = ", ".join(["void* self"] + ([params] if params else []))
            out.append(f"// {demangled}")
            out.append(f"inline {rtype} {fname}({decl}) {{ return reinterpret_cast<{rtype}(__fastcall*)({sig})>(g_fn[{i}])({call}); }}")
        else:
            sig = ", ".join(ptypes) or "void"
            out.append(f"// {demangled}")
            out.append(f"inline {rtype} {fname}({params}) {{ return reinterpret_cast<{rtype}(__cdecl*)({sig})>(g_fn[{i}])({args}); }}")
        table.append(f'    {{"{mangled}"}},')
    out += ["", "}  // namespace rnative::orig", ""]
    (ROOT / "proxy/native/orig_api.gen.h").write_text("\n".join(out))
    cpp = ["// Generated by tools/gen_orig_api.py - do not edit.", '#include "native/orig_api.gen.h"',
           '#include "native/native.h"', "", "namespace rnative::orig {", "", "void* g_fn[kExportCount];",
           "const ExportName kExports[kExportCount] = {", *table, "};", "",
           "bool Init(HMODULE orig)", "{", "    bool ok = true;", "    for (unsigned i = 0; i < kExportCount; ++i) {",
           "        g_fn[i] = reinterpret_cast<void*>(GetProcAddress(orig, kExports[i].mangled));",
           "        if (!g_fn[i]) { ok = false; Log(\"orig api: %s missing\", kExports[i].mangled); }", "    }",
           "    return ok;", "}", "", "}  // namespace rnative::orig", ""]
    (ROOT / "proxy/native/orig_api.gen.cpp").write_text("\n".join(cpp))
    print(f"{len(funcs)} functions bound")


main()
