#!/usr/bin/env python3
"""Generate pass-through COM wrappers for the DirectDraw 7 / Direct3D 7 interfaces Randy uses.

Parses the interface declarations in the Windows SDK's ddraw.h and d3d.h (so vtable order is exactly the
SDK's) and writes proxy/ddraw/com_trace.gen.h:
  - one class Trace<Interface> per interface, deriving from the SDK interface, holding the real object;
  - every method counts its call (g_comCalls[index]) and forwards to the real object, unwrapping interface
    pointers passed in and wrapping interface pointers handed out;
  - methods listed in MANUAL are only declared; proxy/ddraw/com_trace.cpp implements them;
  - kComMethodNames[] lists "Interface::Method" for every counter index.

Usage: tools/gen_com_trace.py [SDK_UM_INCLUDE_DIR]   (default ~/.xwin/sdk/include/um)
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SDK = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else pathlib.Path.home() / ".xwin/sdk/include/um")

INTERFACES = [  # (header, interface)
    ("ddraw.h", "IDirectDraw7"),
    ("ddraw.h", "IDirectDrawSurface7"),
    ("ddraw.h", "IDirectDrawClipper"),
    ("ddraw.h", "IDirectDrawPalette"),
    ("d3d.h", "IDirect3D7"),
    ("d3d.h", "IDirect3DDevice7"),
    ("d3d.h", "IDirect3DVertexBuffer7"),
]

# Interface pointer types: (type name as written in the SDK, interface)
IN_TYPES = {
    "LPDIRECTDRAWSURFACE7": "IDirectDrawSurface7",
    "LPDIRECTDRAWCLIPPER": "IDirectDrawClipper",
    "LPDIRECTDRAWPALETTE": "IDirectDrawPalette",
    "LPDIRECT3DDEVICE7": "IDirect3DDevice7",
    "LPDIRECT3DVERTEXBUFFER7": "IDirect3DVertexBuffer7",
}
OUT_TYPES = {f"{k}*": v for k, v in IN_TYPES.items()}
OUT_TYPES.update({"LPDIRECT3D7*": "IDirect3D7", "LPDIRECTDRAW7*": "IDirectDraw7"})

# Implemented by hand in com_trace.cpp (identity, refcounting, callbacks handing out surfaces, untyped outs).
MANUAL = {
    "*": {"QueryInterface", "AddRef", "Release"},
    "IDirectDraw7": {"EnumSurfaces"},
    "IDirectDrawSurface7": {"EnumAttachedSurfaces", "EnumOverlayZOrders", "GetDDInterface", "BltBatch"},
}


# Methods whose arguments are logged (after the real call) by TraceDetail_<Interface>_<Method>(self, result, args...)
# in com_trace.cpp.
DETAIL = {
    "IDirectDraw7": {"CreateSurface", "SetCooperativeLevel", "SetDisplayMode", "GetAvailableVidMem"},
    "IDirectDrawSurface7": {"Lock", "Blt", "BltFast", "GetAttachedSurface", "SetPrivateData", "AddAttachedSurface",
                            "Flip", "GetDC", "SetColorKey", "SetPalette"},
    "IDirect3D7": {"CreateDevice", "CreateVertexBuffer"},
    "IDirect3DDevice7": {"SetRenderTarget", "DrawPrimitive", "DrawIndexedPrimitive", "Load", "PreLoad"},
    "IDirect3DVertexBuffer7": {"Lock", "ProcessVertices"},
}


def parse(header, name):
    text = (SDK / header).read_text(errors="replace")
    m = re.search(r"DECLARE_INTERFACE_\(\s*%s\s*,\s*\w+\s*\)\s*\{(.*?)\n\};" % name, text, re.S)
    if not m:
        sys.exit(f"{name} not found in {header}")
    body = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)
    methods = []
    for mm in re.finditer(r"STDMETHOD(_)?\((.*?)\)\s*\((.*?)\)\s*PURE\s*;", body, re.S):
        if mm.group(1):
            ret, mname = [s.strip() for s in mm.group(2).split(",")]
        else:
            ret, mname = "HRESULT", mm.group(2).strip()
        args = " ".join(mm.group(3).split())
        args = re.sub(r"^THIS_?\s*,?\s*", "", args)
        params = []
        if args and args != "THIS":
            for i, a in enumerate(split_args(args)):
                a = a.replace("FAR", " ").strip()
                a = " ".join(a.split())
                # Split "TYPE name" / "TYPE * name" / "TYPE" into type and name.
                t = re.match(r"^(.*?)(\b[A-Za-z_]\w*)?$", a)
                typ, pname = a, None
                words = a.replace("*", " * ").split()
                if len(words) >= 2 and re.match(r"^[a-z_]\w*$", words[-1]) and words[-2] != "*" or \
                   (len(words) >= 2 and re.match(r"^[a-z]\w*$", words[-1])):
                    pname = words[-1]
                    typ = " ".join(words[:-1])
                typ = typ.replace(" *", "*").replace("* ", "*")
                params.append((typ, f"a{i}"))
        methods.append((ret, mname, params))
    return methods


def split_args(s):
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
            continue
        depth += ch == "("
        depth -= ch == ")"
        cur += ch
    if cur.strip():
        out.append(cur)
    return out


def main():
    lines = ["// Generated by tools/gen_com_trace.py from the Windows SDK's ddraw.h / d3d.h. Do not edit.",
             "#pragma once", ""]
    names = []
    classes = []
    for header, iface in INTERFACES:
        methods = parse(header, iface)
        manual = MANUAL["*"] | MANUAL.get(iface, set())
        cls = [f"class Trace{iface} final : public {iface}, public TraceBase<{iface}> {{",
               "public:",
               f"    using TraceBase::TraceBase;",
               f"    static constexpr const char* kName = \"{iface}\";"]
        for ret, mname, params in methods:
            idx = len(names)
            names.append(f"{iface}::{mname}")
            sig = ", ".join(f"{t} {n}" for t, n in params)
            decl = f"    COM_DECLSPEC_NOTHROW {ret} STDMETHODCALLTYPE {mname}({sig}) override"
            if mname in manual:
                cls.append(decl + ";" + f"   // manual, counter {idx}")
                continue
            pre, call, post = [], [], []
            for t, n in params:
                if t in IN_TYPES:
                    call.append(f"Unwrap<Trace{IN_TYPES[t]}>({n})")
                elif t in OUT_TYPES:
                    call.append(n)
                    post.append(f"        if (SUCCEEDED(r) && {n} && *{n}) *{n} = Wrap<Trace{OUT_TYPES[t]}>(*{n});")
                else:
                    call.append(n)
            body = [decl, "    {", f"        CountComCall({idx});"]
            if mname in DETAIL.get(iface, set()):
                body.append(f"        {ret} r = m_real->{mname}({', '.join(call)});")
                body.append(f"        TraceDetail_{iface}_{mname}(this, r{''.join(', ' + n for _, n in params)});")
                body += post
                body.append("        return r;")
            elif post:
                body.append(f"        {ret} r = m_real->{mname}({', '.join(call)});")
                body += post
                body.append("        return r;")
            else:
                body.append(f"        return m_real->{mname}({', '.join(call)});")
            body.append("    }")
            cls += body
        cls.append("};")
        cls.append("")
        classes += cls
    lines.append(f"constexpr unsigned kComMethodCount = {len(names)};")
    lines.append("")
    # Forward declarations so wrappers can reference each other.
    for _, iface in INTERFACES:
        lines.append(f"class Trace{iface};")
    lines.append("")
    for header, iface in INTERFACES:
        for ret, mname, params in parse(header, iface):
            if mname in DETAIL.get(iface, set()):
                sig = "".join(f", {t} {n}" for t, n in params)
                lines.append(f"void TraceDetail_{iface}_{mname}(Trace{iface}* self, {ret} r{sig});")
    lines.append("")
    lines += classes
    lines.append("#ifdef RVK_COM_TRACE_NAMES")
    lines.append("const char* const kComMethodNames[kComMethodCount] = {")
    lines += [f'    "{n}",' for n in names]
    lines.append("};")
    lines.append("#endif")
    out = ROOT / "proxy/ddraw/com_trace.gen.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"{len(names)} methods in {len(INTERFACES)} interfaces -> {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
