// Generated by tools/gen_com_trace.py from the Windows SDK's ddraw.h / d3d.h. Do not edit.
#pragma once

constexpr unsigned kComMethodCount = 161;

class TraceIDirectDraw7;
class TraceIDirectDrawSurface7;
class TraceIDirectDrawClipper;
class TraceIDirectDrawPalette;
class TraceIDirect3D7;
class TraceIDirect3DDevice7;
class TraceIDirect3DVertexBuffer7;

class TraceIDirectDraw7 final : public IDirectDraw7, public TraceBase<IDirectDraw7> {
public:
    using TraceBase::TraceBase;
    static constexpr const char* kName = "IDirectDraw7";
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE QueryInterface(REFIID a0, LPVOID* a1) override;   // manual, counter 0
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE AddRef() override;   // manual, counter 1
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE Release() override;   // manual, counter 2
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Compact() override
    {
        CountComCall(3);
        return m_real->Compact();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE CreateClipper(DWORD a0, LPDIRECTDRAWCLIPPER* a1, IUnknown* a2) override
    {
        CountComCall(4);
        HRESULT r = m_real->CreateClipper(a0, a1, a2);
        if (SUCCEEDED(r) && a1 && *a1) *a1 = Wrap<TraceIDirectDrawClipper>(*a1);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE CreatePalette(DWORD a0, LPPALETTEENTRY a1, LPDIRECTDRAWPALETTE* a2, IUnknown* a3) override
    {
        CountComCall(5);
        HRESULT r = m_real->CreatePalette(a0, a1, a2, a3);
        if (SUCCEEDED(r) && a2 && *a2) *a2 = Wrap<TraceIDirectDrawPalette>(*a2);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE CreateSurface(LPDDSURFACEDESC2 a0, LPDIRECTDRAWSURFACE7* a1, IUnknown* a2) override
    {
        CountComCall(6);
        HRESULT r = m_real->CreateSurface(a0, a1, a2);
        if (SUCCEEDED(r) && a1 && *a1) *a1 = Wrap<TraceIDirectDrawSurface7>(*a1);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE DuplicateSurface(LPDIRECTDRAWSURFACE7 a0, LPDIRECTDRAWSURFACE7* a1) override
    {
        CountComCall(7);
        HRESULT r = m_real->DuplicateSurface(Unwrap<TraceIDirectDrawSurface7>(a0), a1);
        if (SUCCEEDED(r) && a1 && *a1) *a1 = Wrap<TraceIDirectDrawSurface7>(*a1);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumDisplayModes(DWORD a0, LPDDSURFACEDESC2 a1, LPVOID a2, LPDDENUMMODESCALLBACK2 a3) override
    {
        CountComCall(8);
        return m_real->EnumDisplayModes(a0, a1, a2, a3);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumSurfaces(DWORD a0, LPDDSURFACEDESC2 a1, LPVOID a2, LPDDENUMSURFACESCALLBACK7 a3) override;   // manual, counter 9
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE FlipToGDISurface() override
    {
        CountComCall(10);
        return m_real->FlipToGDISurface();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetCaps(LPDDCAPS a0, LPDDCAPS a1) override
    {
        CountComCall(11);
        return m_real->GetCaps(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetDisplayMode(LPDDSURFACEDESC2 a0) override
    {
        CountComCall(12);
        return m_real->GetDisplayMode(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetFourCCCodes(LPDWORD a0, LPDWORD a1) override
    {
        CountComCall(13);
        return m_real->GetFourCCCodes(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetGDISurface(LPDIRECTDRAWSURFACE7* a0) override
    {
        CountComCall(14);
        HRESULT r = m_real->GetGDISurface(a0);
        if (SUCCEEDED(r) && a0 && *a0) *a0 = Wrap<TraceIDirectDrawSurface7>(*a0);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetMonitorFrequency(LPDWORD a0) override
    {
        CountComCall(15);
        return m_real->GetMonitorFrequency(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetScanLine(LPDWORD a0) override
    {
        CountComCall(16);
        return m_real->GetScanLine(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetVerticalBlankStatus(LPBOOL a0) override
    {
        CountComCall(17);
        return m_real->GetVerticalBlankStatus(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Initialize(GUID* a0) override
    {
        CountComCall(18);
        return m_real->Initialize(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE RestoreDisplayMode() override
    {
        CountComCall(19);
        return m_real->RestoreDisplayMode();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetCooperativeLevel(HWND a0, DWORD a1) override
    {
        CountComCall(20);
        return m_real->SetCooperativeLevel(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetDisplayMode(DWORD a0, DWORD a1, DWORD a2, DWORD a3, DWORD a4) override
    {
        CountComCall(21);
        return m_real->SetDisplayMode(a0, a1, a2, a3, a4);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE WaitForVerticalBlank(DWORD a0, HANDLE a1) override
    {
        CountComCall(22);
        return m_real->WaitForVerticalBlank(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetAvailableVidMem(LPDDSCAPS2 a0, LPDWORD a1, LPDWORD a2) override
    {
        CountComCall(23);
        return m_real->GetAvailableVidMem(a0, a1, a2);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetSurfaceFromDC(HDC a0, LPDIRECTDRAWSURFACE7* a1) override
    {
        CountComCall(24);
        HRESULT r = m_real->GetSurfaceFromDC(a0, a1);
        if (SUCCEEDED(r) && a1 && *a1) *a1 = Wrap<TraceIDirectDrawSurface7>(*a1);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE RestoreAllSurfaces() override
    {
        CountComCall(25);
        return m_real->RestoreAllSurfaces();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE TestCooperativeLevel() override
    {
        CountComCall(26);
        return m_real->TestCooperativeLevel();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetDeviceIdentifier(LPDDDEVICEIDENTIFIER2 a0, DWORD a1) override
    {
        CountComCall(27);
        return m_real->GetDeviceIdentifier(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE StartModeTest(LPSIZE a0, DWORD a1, DWORD a2) override
    {
        CountComCall(28);
        return m_real->StartModeTest(a0, a1, a2);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EvaluateMode(DWORD a0, DWORD* a1) override
    {
        CountComCall(29);
        return m_real->EvaluateMode(a0, a1);
    }
};

class TraceIDirectDrawSurface7 final : public IDirectDrawSurface7, public TraceBase<IDirectDrawSurface7> {
public:
    using TraceBase::TraceBase;
    static constexpr const char* kName = "IDirectDrawSurface7";
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE QueryInterface(REFIID a0, LPVOID* a1) override;   // manual, counter 30
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE AddRef() override;   // manual, counter 31
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE Release() override;   // manual, counter 32
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE AddAttachedSurface(LPDIRECTDRAWSURFACE7 a0) override
    {
        CountComCall(33);
        return m_real->AddAttachedSurface(Unwrap<TraceIDirectDrawSurface7>(a0));
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE AddOverlayDirtyRect(LPRECT a0) override
    {
        CountComCall(34);
        return m_real->AddOverlayDirtyRect(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Blt(LPRECT a0, LPDIRECTDRAWSURFACE7 a1, LPRECT a2, DWORD a3, LPDDBLTFX a4) override
    {
        CountComCall(35);
        return m_real->Blt(a0, Unwrap<TraceIDirectDrawSurface7>(a1), a2, a3, a4);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE BltBatch(LPDDBLTBATCH a0, DWORD a1, DWORD a2) override;   // manual, counter 36
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE BltFast(DWORD a0, DWORD a1, LPDIRECTDRAWSURFACE7 a2, LPRECT a3, DWORD a4) override
    {
        CountComCall(37);
        return m_real->BltFast(a0, a1, Unwrap<TraceIDirectDrawSurface7>(a2), a3, a4);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE DeleteAttachedSurface(DWORD a0, LPDIRECTDRAWSURFACE7 a1) override
    {
        CountComCall(38);
        return m_real->DeleteAttachedSurface(a0, Unwrap<TraceIDirectDrawSurface7>(a1));
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumAttachedSurfaces(LPVOID a0, LPDDENUMSURFACESCALLBACK7 a1) override;   // manual, counter 39
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumOverlayZOrders(DWORD a0, LPVOID a1, LPDDENUMSURFACESCALLBACK7 a2) override;   // manual, counter 40
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Flip(LPDIRECTDRAWSURFACE7 a0, DWORD a1) override
    {
        CountComCall(41);
        return m_real->Flip(Unwrap<TraceIDirectDrawSurface7>(a0), a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetAttachedSurface(LPDDSCAPS2 a0, LPDIRECTDRAWSURFACE7* a1) override
    {
        CountComCall(42);
        HRESULT r = m_real->GetAttachedSurface(a0, a1);
        if (SUCCEEDED(r) && a1 && *a1) *a1 = Wrap<TraceIDirectDrawSurface7>(*a1);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetBltStatus(DWORD a0) override
    {
        CountComCall(43);
        return m_real->GetBltStatus(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetCaps(LPDDSCAPS2 a0) override
    {
        CountComCall(44);
        return m_real->GetCaps(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetClipper(LPDIRECTDRAWCLIPPER* a0) override
    {
        CountComCall(45);
        HRESULT r = m_real->GetClipper(a0);
        if (SUCCEEDED(r) && a0 && *a0) *a0 = Wrap<TraceIDirectDrawClipper>(*a0);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetColorKey(DWORD a0, LPDDCOLORKEY a1) override
    {
        CountComCall(46);
        return m_real->GetColorKey(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetDC(HDC* a0) override
    {
        CountComCall(47);
        return m_real->GetDC(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetFlipStatus(DWORD a0) override
    {
        CountComCall(48);
        return m_real->GetFlipStatus(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetOverlayPosition(LPLONG a0, LPLONG a1) override
    {
        CountComCall(49);
        return m_real->GetOverlayPosition(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetPalette(LPDIRECTDRAWPALETTE* a0) override
    {
        CountComCall(50);
        HRESULT r = m_real->GetPalette(a0);
        if (SUCCEEDED(r) && a0 && *a0) *a0 = Wrap<TraceIDirectDrawPalette>(*a0);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetPixelFormat(LPDDPIXELFORMAT a0) override
    {
        CountComCall(51);
        return m_real->GetPixelFormat(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetSurfaceDesc(LPDDSURFACEDESC2 a0) override
    {
        CountComCall(52);
        return m_real->GetSurfaceDesc(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Initialize(LPDIRECTDRAW a0, LPDDSURFACEDESC2 a1) override
    {
        CountComCall(53);
        return m_real->Initialize(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE IsLost() override
    {
        CountComCall(54);
        return m_real->IsLost();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Lock(LPRECT a0, LPDDSURFACEDESC2 a1, DWORD a2, HANDLE a3) override
    {
        CountComCall(55);
        return m_real->Lock(a0, a1, a2, a3);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE ReleaseDC(HDC a0) override
    {
        CountComCall(56);
        return m_real->ReleaseDC(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Restore() override
    {
        CountComCall(57);
        return m_real->Restore();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetClipper(LPDIRECTDRAWCLIPPER a0) override
    {
        CountComCall(58);
        return m_real->SetClipper(Unwrap<TraceIDirectDrawClipper>(a0));
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetColorKey(DWORD a0, LPDDCOLORKEY a1) override
    {
        CountComCall(59);
        return m_real->SetColorKey(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetOverlayPosition(LONG a0, LONG a1) override
    {
        CountComCall(60);
        return m_real->SetOverlayPosition(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetPalette(LPDIRECTDRAWPALETTE a0) override
    {
        CountComCall(61);
        return m_real->SetPalette(Unwrap<TraceIDirectDrawPalette>(a0));
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Unlock(LPRECT a0) override
    {
        CountComCall(62);
        return m_real->Unlock(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE UpdateOverlay(LPRECT a0, LPDIRECTDRAWSURFACE7 a1, LPRECT a2, DWORD a3, LPDDOVERLAYFX a4) override
    {
        CountComCall(63);
        return m_real->UpdateOverlay(a0, Unwrap<TraceIDirectDrawSurface7>(a1), a2, a3, a4);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE UpdateOverlayDisplay(DWORD a0) override
    {
        CountComCall(64);
        return m_real->UpdateOverlayDisplay(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE UpdateOverlayZOrder(DWORD a0, LPDIRECTDRAWSURFACE7 a1) override
    {
        CountComCall(65);
        return m_real->UpdateOverlayZOrder(a0, Unwrap<TraceIDirectDrawSurface7>(a1));
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetDDInterface(LPVOID* a0) override;   // manual, counter 66
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE PageLock(DWORD a0) override
    {
        CountComCall(67);
        return m_real->PageLock(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE PageUnlock(DWORD a0) override
    {
        CountComCall(68);
        return m_real->PageUnlock(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetSurfaceDesc(LPDDSURFACEDESC2 a0, DWORD a1) override
    {
        CountComCall(69);
        return m_real->SetSurfaceDesc(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetPrivateData(REFGUID a0, LPVOID a1, DWORD a2, DWORD a3) override
    {
        CountComCall(70);
        return m_real->SetPrivateData(a0, a1, a2, a3);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetPrivateData(REFGUID a0, LPVOID a1, LPDWORD a2) override
    {
        CountComCall(71);
        return m_real->GetPrivateData(a0, a1, a2);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE FreePrivateData(REFGUID a0) override
    {
        CountComCall(72);
        return m_real->FreePrivateData(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetUniquenessValue(LPDWORD a0) override
    {
        CountComCall(73);
        return m_real->GetUniquenessValue(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE ChangeUniquenessValue() override
    {
        CountComCall(74);
        return m_real->ChangeUniquenessValue();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetPriority(DWORD a0) override
    {
        CountComCall(75);
        return m_real->SetPriority(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetPriority(LPDWORD a0) override
    {
        CountComCall(76);
        return m_real->GetPriority(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetLOD(DWORD a0) override
    {
        CountComCall(77);
        return m_real->SetLOD(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetLOD(LPDWORD a0) override
    {
        CountComCall(78);
        return m_real->GetLOD(a0);
    }
};

class TraceIDirectDrawClipper final : public IDirectDrawClipper, public TraceBase<IDirectDrawClipper> {
public:
    using TraceBase::TraceBase;
    static constexpr const char* kName = "IDirectDrawClipper";
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE QueryInterface(REFIID a0, LPVOID* a1) override;   // manual, counter 79
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE AddRef() override;   // manual, counter 80
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE Release() override;   // manual, counter 81
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetClipList(LPRECT a0, LPRGNDATA a1, LPDWORD a2) override
    {
        CountComCall(82);
        return m_real->GetClipList(a0, a1, a2);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetHWnd(HWND* a0) override
    {
        CountComCall(83);
        return m_real->GetHWnd(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Initialize(LPDIRECTDRAW a0, DWORD a1) override
    {
        CountComCall(84);
        return m_real->Initialize(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE IsClipListChanged(BOOL* a0) override
    {
        CountComCall(85);
        return m_real->IsClipListChanged(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetClipList(LPRGNDATA a0, DWORD a1) override
    {
        CountComCall(86);
        return m_real->SetClipList(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetHWnd(DWORD a0, HWND a1) override
    {
        CountComCall(87);
        return m_real->SetHWnd(a0, a1);
    }
};

class TraceIDirectDrawPalette final : public IDirectDrawPalette, public TraceBase<IDirectDrawPalette> {
public:
    using TraceBase::TraceBase;
    static constexpr const char* kName = "IDirectDrawPalette";
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE QueryInterface(REFIID a0, LPVOID* a1) override;   // manual, counter 88
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE AddRef() override;   // manual, counter 89
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE Release() override;   // manual, counter 90
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetCaps(LPDWORD a0) override
    {
        CountComCall(91);
        return m_real->GetCaps(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetEntries(DWORD a0, DWORD a1, DWORD a2, LPPALETTEENTRY a3) override
    {
        CountComCall(92);
        return m_real->GetEntries(a0, a1, a2, a3);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Initialize(LPDIRECTDRAW a0, DWORD a1, LPPALETTEENTRY a2) override
    {
        CountComCall(93);
        return m_real->Initialize(a0, a1, a2);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetEntries(DWORD a0, DWORD a1, DWORD a2, LPPALETTEENTRY a3) override
    {
        CountComCall(94);
        return m_real->SetEntries(a0, a1, a2, a3);
    }
};

class TraceIDirect3D7 final : public IDirect3D7, public TraceBase<IDirect3D7> {
public:
    using TraceBase::TraceBase;
    static constexpr const char* kName = "IDirect3D7";
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE QueryInterface(REFIID a0, LPVOID* a1) override;   // manual, counter 95
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE AddRef() override;   // manual, counter 96
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE Release() override;   // manual, counter 97
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumDevices(LPD3DENUMDEVICESCALLBACK7 a0, LPVOID a1) override
    {
        CountComCall(98);
        return m_real->EnumDevices(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE CreateDevice(REFCLSID a0, LPDIRECTDRAWSURFACE7 a1, LPDIRECT3DDEVICE7* a2) override
    {
        CountComCall(99);
        HRESULT r = m_real->CreateDevice(a0, Unwrap<TraceIDirectDrawSurface7>(a1), a2);
        if (SUCCEEDED(r) && a2 && *a2) *a2 = Wrap<TraceIDirect3DDevice7>(*a2);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE CreateVertexBuffer(LPD3DVERTEXBUFFERDESC a0, LPDIRECT3DVERTEXBUFFER7* a1, DWORD a2) override
    {
        CountComCall(100);
        HRESULT r = m_real->CreateVertexBuffer(a0, a1, a2);
        if (SUCCEEDED(r) && a1 && *a1) *a1 = Wrap<TraceIDirect3DVertexBuffer7>(*a1);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumZBufferFormats(REFCLSID a0, LPD3DENUMPIXELFORMATSCALLBACK a1, LPVOID a2) override
    {
        CountComCall(101);
        return m_real->EnumZBufferFormats(a0, a1, a2);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EvictManagedTextures() override
    {
        CountComCall(102);
        return m_real->EvictManagedTextures();
    }
};

class TraceIDirect3DDevice7 final : public IDirect3DDevice7, public TraceBase<IDirect3DDevice7> {
public:
    using TraceBase::TraceBase;
    static constexpr const char* kName = "IDirect3DDevice7";
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE QueryInterface(REFIID a0, LPVOID* a1) override;   // manual, counter 103
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE AddRef() override;   // manual, counter 104
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE Release() override;   // manual, counter 105
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetCaps(LPD3DDEVICEDESC7 a0) override
    {
        CountComCall(106);
        return m_real->GetCaps(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EnumTextureFormats(LPD3DENUMPIXELFORMATSCALLBACK a0, LPVOID a1) override
    {
        CountComCall(107);
        return m_real->EnumTextureFormats(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE BeginScene() override
    {
        CountComCall(108);
        return m_real->BeginScene();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EndScene() override
    {
        CountComCall(109);
        return m_real->EndScene();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetDirect3D(LPDIRECT3D7* a0) override
    {
        CountComCall(110);
        HRESULT r = m_real->GetDirect3D(a0);
        if (SUCCEEDED(r) && a0 && *a0) *a0 = Wrap<TraceIDirect3D7>(*a0);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetRenderTarget(LPDIRECTDRAWSURFACE7 a0, DWORD a1) override
    {
        CountComCall(111);
        return m_real->SetRenderTarget(Unwrap<TraceIDirectDrawSurface7>(a0), a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetRenderTarget(LPDIRECTDRAWSURFACE7* a0) override
    {
        CountComCall(112);
        HRESULT r = m_real->GetRenderTarget(a0);
        if (SUCCEEDED(r) && a0 && *a0) *a0 = Wrap<TraceIDirectDrawSurface7>(*a0);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Clear(DWORD a0, LPD3DRECT a1, DWORD a2, D3DCOLOR a3, D3DVALUE a4, DWORD a5) override
    {
        CountComCall(113);
        return m_real->Clear(a0, a1, a2, a3, a4, a5);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetTransform(D3DTRANSFORMSTATETYPE a0, LPD3DMATRIX a1) override
    {
        CountComCall(114);
        return m_real->SetTransform(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetTransform(D3DTRANSFORMSTATETYPE a0, LPD3DMATRIX a1) override
    {
        CountComCall(115);
        return m_real->GetTransform(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetViewport(LPD3DVIEWPORT7 a0) override
    {
        CountComCall(116);
        return m_real->SetViewport(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE MultiplyTransform(D3DTRANSFORMSTATETYPE a0, LPD3DMATRIX a1) override
    {
        CountComCall(117);
        return m_real->MultiplyTransform(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetViewport(LPD3DVIEWPORT7 a0) override
    {
        CountComCall(118);
        return m_real->GetViewport(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetMaterial(LPD3DMATERIAL7 a0) override
    {
        CountComCall(119);
        return m_real->SetMaterial(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetMaterial(LPD3DMATERIAL7 a0) override
    {
        CountComCall(120);
        return m_real->GetMaterial(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetLight(DWORD a0, LPD3DLIGHT7 a1) override
    {
        CountComCall(121);
        return m_real->SetLight(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetLight(DWORD a0, LPD3DLIGHT7 a1) override
    {
        CountComCall(122);
        return m_real->GetLight(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetRenderState(D3DRENDERSTATETYPE a0, DWORD a1) override
    {
        CountComCall(123);
        return m_real->SetRenderState(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetRenderState(D3DRENDERSTATETYPE a0, LPDWORD a1) override
    {
        CountComCall(124);
        return m_real->GetRenderState(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE BeginStateBlock() override
    {
        CountComCall(125);
        return m_real->BeginStateBlock();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE EndStateBlock(LPDWORD a0) override
    {
        CountComCall(126);
        return m_real->EndStateBlock(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE PreLoad(LPDIRECTDRAWSURFACE7 a0) override
    {
        CountComCall(127);
        return m_real->PreLoad(Unwrap<TraceIDirectDrawSurface7>(a0));
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE DrawPrimitive(D3DPRIMITIVETYPE a0, DWORD a1, LPVOID a2, DWORD a3, DWORD a4) override
    {
        CountComCall(128);
        return m_real->DrawPrimitive(a0, a1, a2, a3, a4);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE DrawIndexedPrimitive(D3DPRIMITIVETYPE a0, DWORD a1, LPVOID a2, DWORD a3, LPWORD a4, DWORD a5, DWORD a6) override
    {
        CountComCall(129);
        return m_real->DrawIndexedPrimitive(a0, a1, a2, a3, a4, a5, a6);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetClipStatus(LPD3DCLIPSTATUS a0) override
    {
        CountComCall(130);
        return m_real->SetClipStatus(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetClipStatus(LPD3DCLIPSTATUS a0) override
    {
        CountComCall(131);
        return m_real->GetClipStatus(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE DrawPrimitiveStrided(D3DPRIMITIVETYPE a0, DWORD a1, LPD3DDRAWPRIMITIVESTRIDEDDATA a2, DWORD a3, DWORD a4) override
    {
        CountComCall(132);
        return m_real->DrawPrimitiveStrided(a0, a1, a2, a3, a4);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE DrawIndexedPrimitiveStrided(D3DPRIMITIVETYPE a0, DWORD a1, LPD3DDRAWPRIMITIVESTRIDEDDATA a2, DWORD a3, LPWORD a4, DWORD a5, DWORD a6) override
    {
        CountComCall(133);
        return m_real->DrawIndexedPrimitiveStrided(a0, a1, a2, a3, a4, a5, a6);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE DrawPrimitiveVB(D3DPRIMITIVETYPE a0, LPDIRECT3DVERTEXBUFFER7 a1, DWORD a2, DWORD a3, DWORD a4) override
    {
        CountComCall(134);
        return m_real->DrawPrimitiveVB(a0, Unwrap<TraceIDirect3DVertexBuffer7>(a1), a2, a3, a4);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE DrawIndexedPrimitiveVB(D3DPRIMITIVETYPE a0, LPDIRECT3DVERTEXBUFFER7 a1, DWORD a2, DWORD a3, LPWORD a4, DWORD a5, DWORD a6) override
    {
        CountComCall(135);
        return m_real->DrawIndexedPrimitiveVB(a0, Unwrap<TraceIDirect3DVertexBuffer7>(a1), a2, a3, a4, a5, a6);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE ComputeSphereVisibility(LPD3DVECTOR a0, LPD3DVALUE a1, DWORD a2, DWORD a3, LPDWORD a4) override
    {
        CountComCall(136);
        return m_real->ComputeSphereVisibility(a0, a1, a2, a3, a4);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetTexture(DWORD a0, LPDIRECTDRAWSURFACE7* a1) override
    {
        CountComCall(137);
        HRESULT r = m_real->GetTexture(a0, a1);
        if (SUCCEEDED(r) && a1 && *a1) *a1 = Wrap<TraceIDirectDrawSurface7>(*a1);
        return r;
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetTexture(DWORD a0, LPDIRECTDRAWSURFACE7 a1) override
    {
        CountComCall(138);
        return m_real->SetTexture(a0, Unwrap<TraceIDirectDrawSurface7>(a1));
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetTextureStageState(DWORD a0, D3DTEXTURESTAGESTATETYPE a1, LPDWORD a2) override
    {
        CountComCall(139);
        return m_real->GetTextureStageState(a0, a1, a2);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetTextureStageState(DWORD a0, D3DTEXTURESTAGESTATETYPE a1, DWORD a2) override
    {
        CountComCall(140);
        return m_real->SetTextureStageState(a0, a1, a2);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE ValidateDevice(LPDWORD a0) override
    {
        CountComCall(141);
        return m_real->ValidateDevice(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE ApplyStateBlock(DWORD a0) override
    {
        CountComCall(142);
        return m_real->ApplyStateBlock(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE CaptureStateBlock(DWORD a0) override
    {
        CountComCall(143);
        return m_real->CaptureStateBlock(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE DeleteStateBlock(DWORD a0) override
    {
        CountComCall(144);
        return m_real->DeleteStateBlock(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE CreateStateBlock(D3DSTATEBLOCKTYPE a0, LPDWORD a1) override
    {
        CountComCall(145);
        return m_real->CreateStateBlock(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Load(LPDIRECTDRAWSURFACE7 a0, LPPOINT a1, LPDIRECTDRAWSURFACE7 a2, LPRECT a3, DWORD a4) override
    {
        CountComCall(146);
        return m_real->Load(Unwrap<TraceIDirectDrawSurface7>(a0), a1, Unwrap<TraceIDirectDrawSurface7>(a2), a3, a4);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE LightEnable(DWORD a0, BOOL a1) override
    {
        CountComCall(147);
        return m_real->LightEnable(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetLightEnable(DWORD a0, BOOL* a1) override
    {
        CountComCall(148);
        return m_real->GetLightEnable(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE SetClipPlane(DWORD a0, D3DVALUE* a1) override
    {
        CountComCall(149);
        return m_real->SetClipPlane(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetClipPlane(DWORD a0, D3DVALUE* a1) override
    {
        CountComCall(150);
        return m_real->GetClipPlane(a0, a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetInfo(DWORD a0, LPVOID a1, DWORD a2) override
    {
        CountComCall(151);
        return m_real->GetInfo(a0, a1, a2);
    }
};

class TraceIDirect3DVertexBuffer7 final : public IDirect3DVertexBuffer7, public TraceBase<IDirect3DVertexBuffer7> {
public:
    using TraceBase::TraceBase;
    static constexpr const char* kName = "IDirect3DVertexBuffer7";
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE QueryInterface(REFIID a0, LPVOID* a1) override;   // manual, counter 152
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE AddRef() override;   // manual, counter 153
    COM_DECLSPEC_NOTHROW ULONG STDMETHODCALLTYPE Release() override;   // manual, counter 154
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Lock(DWORD a0, LPVOID* a1, LPDWORD a2) override
    {
        CountComCall(155);
        return m_real->Lock(a0, a1, a2);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Unlock() override
    {
        CountComCall(156);
        return m_real->Unlock();
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE ProcessVertices(DWORD a0, DWORD a1, DWORD a2, LPDIRECT3DVERTEXBUFFER7 a3, DWORD a4, LPDIRECT3DDEVICE7 a5, DWORD a6) override
    {
        CountComCall(157);
        return m_real->ProcessVertices(a0, a1, a2, Unwrap<TraceIDirect3DVertexBuffer7>(a3), a4, Unwrap<TraceIDirect3DDevice7>(a5), a6);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE GetVertexBufferDesc(LPD3DVERTEXBUFFERDESC a0) override
    {
        CountComCall(158);
        return m_real->GetVertexBufferDesc(a0);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE Optimize(LPDIRECT3DDEVICE7 a0, DWORD a1) override
    {
        CountComCall(159);
        return m_real->Optimize(Unwrap<TraceIDirect3DDevice7>(a0), a1);
    }
    COM_DECLSPEC_NOTHROW HRESULT STDMETHODCALLTYPE ProcessVerticesStrided(DWORD a0, DWORD a1, DWORD a2, LPD3DDRAWPRIMITIVESTRIDEDDATA a3, DWORD a4, LPDIRECT3DDEVICE7 a5, DWORD a6) override
    {
        CountComCall(160);
        return m_real->ProcessVerticesStrided(a0, a1, a2, a3, a4, Unwrap<TraceIDirect3DDevice7>(a5), a6);
    }
};

#ifdef RVK_COM_TRACE_NAMES
const char* const kComMethodNames[kComMethodCount] = {
    "IDirectDraw7::QueryInterface",
    "IDirectDraw7::AddRef",
    "IDirectDraw7::Release",
    "IDirectDraw7::Compact",
    "IDirectDraw7::CreateClipper",
    "IDirectDraw7::CreatePalette",
    "IDirectDraw7::CreateSurface",
    "IDirectDraw7::DuplicateSurface",
    "IDirectDraw7::EnumDisplayModes",
    "IDirectDraw7::EnumSurfaces",
    "IDirectDraw7::FlipToGDISurface",
    "IDirectDraw7::GetCaps",
    "IDirectDraw7::GetDisplayMode",
    "IDirectDraw7::GetFourCCCodes",
    "IDirectDraw7::GetGDISurface",
    "IDirectDraw7::GetMonitorFrequency",
    "IDirectDraw7::GetScanLine",
    "IDirectDraw7::GetVerticalBlankStatus",
    "IDirectDraw7::Initialize",
    "IDirectDraw7::RestoreDisplayMode",
    "IDirectDraw7::SetCooperativeLevel",
    "IDirectDraw7::SetDisplayMode",
    "IDirectDraw7::WaitForVerticalBlank",
    "IDirectDraw7::GetAvailableVidMem",
    "IDirectDraw7::GetSurfaceFromDC",
    "IDirectDraw7::RestoreAllSurfaces",
    "IDirectDraw7::TestCooperativeLevel",
    "IDirectDraw7::GetDeviceIdentifier",
    "IDirectDraw7::StartModeTest",
    "IDirectDraw7::EvaluateMode",
    "IDirectDrawSurface7::QueryInterface",
    "IDirectDrawSurface7::AddRef",
    "IDirectDrawSurface7::Release",
    "IDirectDrawSurface7::AddAttachedSurface",
    "IDirectDrawSurface7::AddOverlayDirtyRect",
    "IDirectDrawSurface7::Blt",
    "IDirectDrawSurface7::BltBatch",
    "IDirectDrawSurface7::BltFast",
    "IDirectDrawSurface7::DeleteAttachedSurface",
    "IDirectDrawSurface7::EnumAttachedSurfaces",
    "IDirectDrawSurface7::EnumOverlayZOrders",
    "IDirectDrawSurface7::Flip",
    "IDirectDrawSurface7::GetAttachedSurface",
    "IDirectDrawSurface7::GetBltStatus",
    "IDirectDrawSurface7::GetCaps",
    "IDirectDrawSurface7::GetClipper",
    "IDirectDrawSurface7::GetColorKey",
    "IDirectDrawSurface7::GetDC",
    "IDirectDrawSurface7::GetFlipStatus",
    "IDirectDrawSurface7::GetOverlayPosition",
    "IDirectDrawSurface7::GetPalette",
    "IDirectDrawSurface7::GetPixelFormat",
    "IDirectDrawSurface7::GetSurfaceDesc",
    "IDirectDrawSurface7::Initialize",
    "IDirectDrawSurface7::IsLost",
    "IDirectDrawSurface7::Lock",
    "IDirectDrawSurface7::ReleaseDC",
    "IDirectDrawSurface7::Restore",
    "IDirectDrawSurface7::SetClipper",
    "IDirectDrawSurface7::SetColorKey",
    "IDirectDrawSurface7::SetOverlayPosition",
    "IDirectDrawSurface7::SetPalette",
    "IDirectDrawSurface7::Unlock",
    "IDirectDrawSurface7::UpdateOverlay",
    "IDirectDrawSurface7::UpdateOverlayDisplay",
    "IDirectDrawSurface7::UpdateOverlayZOrder",
    "IDirectDrawSurface7::GetDDInterface",
    "IDirectDrawSurface7::PageLock",
    "IDirectDrawSurface7::PageUnlock",
    "IDirectDrawSurface7::SetSurfaceDesc",
    "IDirectDrawSurface7::SetPrivateData",
    "IDirectDrawSurface7::GetPrivateData",
    "IDirectDrawSurface7::FreePrivateData",
    "IDirectDrawSurface7::GetUniquenessValue",
    "IDirectDrawSurface7::ChangeUniquenessValue",
    "IDirectDrawSurface7::SetPriority",
    "IDirectDrawSurface7::GetPriority",
    "IDirectDrawSurface7::SetLOD",
    "IDirectDrawSurface7::GetLOD",
    "IDirectDrawClipper::QueryInterface",
    "IDirectDrawClipper::AddRef",
    "IDirectDrawClipper::Release",
    "IDirectDrawClipper::GetClipList",
    "IDirectDrawClipper::GetHWnd",
    "IDirectDrawClipper::Initialize",
    "IDirectDrawClipper::IsClipListChanged",
    "IDirectDrawClipper::SetClipList",
    "IDirectDrawClipper::SetHWnd",
    "IDirectDrawPalette::QueryInterface",
    "IDirectDrawPalette::AddRef",
    "IDirectDrawPalette::Release",
    "IDirectDrawPalette::GetCaps",
    "IDirectDrawPalette::GetEntries",
    "IDirectDrawPalette::Initialize",
    "IDirectDrawPalette::SetEntries",
    "IDirect3D7::QueryInterface",
    "IDirect3D7::AddRef",
    "IDirect3D7::Release",
    "IDirect3D7::EnumDevices",
    "IDirect3D7::CreateDevice",
    "IDirect3D7::CreateVertexBuffer",
    "IDirect3D7::EnumZBufferFormats",
    "IDirect3D7::EvictManagedTextures",
    "IDirect3DDevice7::QueryInterface",
    "IDirect3DDevice7::AddRef",
    "IDirect3DDevice7::Release",
    "IDirect3DDevice7::GetCaps",
    "IDirect3DDevice7::EnumTextureFormats",
    "IDirect3DDevice7::BeginScene",
    "IDirect3DDevice7::EndScene",
    "IDirect3DDevice7::GetDirect3D",
    "IDirect3DDevice7::SetRenderTarget",
    "IDirect3DDevice7::GetRenderTarget",
    "IDirect3DDevice7::Clear",
    "IDirect3DDevice7::SetTransform",
    "IDirect3DDevice7::GetTransform",
    "IDirect3DDevice7::SetViewport",
    "IDirect3DDevice7::MultiplyTransform",
    "IDirect3DDevice7::GetViewport",
    "IDirect3DDevice7::SetMaterial",
    "IDirect3DDevice7::GetMaterial",
    "IDirect3DDevice7::SetLight",
    "IDirect3DDevice7::GetLight",
    "IDirect3DDevice7::SetRenderState",
    "IDirect3DDevice7::GetRenderState",
    "IDirect3DDevice7::BeginStateBlock",
    "IDirect3DDevice7::EndStateBlock",
    "IDirect3DDevice7::PreLoad",
    "IDirect3DDevice7::DrawPrimitive",
    "IDirect3DDevice7::DrawIndexedPrimitive",
    "IDirect3DDevice7::SetClipStatus",
    "IDirect3DDevice7::GetClipStatus",
    "IDirect3DDevice7::DrawPrimitiveStrided",
    "IDirect3DDevice7::DrawIndexedPrimitiveStrided",
    "IDirect3DDevice7::DrawPrimitiveVB",
    "IDirect3DDevice7::DrawIndexedPrimitiveVB",
    "IDirect3DDevice7::ComputeSphereVisibility",
    "IDirect3DDevice7::GetTexture",
    "IDirect3DDevice7::SetTexture",
    "IDirect3DDevice7::GetTextureStageState",
    "IDirect3DDevice7::SetTextureStageState",
    "IDirect3DDevice7::ValidateDevice",
    "IDirect3DDevice7::ApplyStateBlock",
    "IDirect3DDevice7::CaptureStateBlock",
    "IDirect3DDevice7::DeleteStateBlock",
    "IDirect3DDevice7::CreateStateBlock",
    "IDirect3DDevice7::Load",
    "IDirect3DDevice7::LightEnable",
    "IDirect3DDevice7::GetLightEnable",
    "IDirect3DDevice7::SetClipPlane",
    "IDirect3DDevice7::GetClipPlane",
    "IDirect3DDevice7::GetInfo",
    "IDirect3DVertexBuffer7::QueryInterface",
    "IDirect3DVertexBuffer7::AddRef",
    "IDirect3DVertexBuffer7::Release",
    "IDirect3DVertexBuffer7::Lock",
    "IDirect3DVertexBuffer7::Unlock",
    "IDirect3DVertexBuffer7::ProcessVertices",
    "IDirect3DVertexBuffer7::GetVertexBufferDesc",
    "IDirect3DVertexBuffer7::Optimize",
    "IDirect3DVertexBuffer7::ProcessVerticesStrided",
};
#endif
